### ISSUE TITLE
Missing struct msghdr

### ISSUE THREAD

**Issue by dignifiedquire** [sunfishcode/linux-raw-sys#12]
I am looking to implement `sendmsg` and `recvmsg` for rustix, and as far as I understand structs like `msghdr` should be pulled from this crate for the implementation of `linux_raw` backend. 

Please let me know if this assumption is correct, and if so what the steps are to getting it added.

**Comment by bjorn3** [comment]
I think it is defined by libc and not by the linux headers. I can find a definition in `/usr/include/x86_64-linux-gnu/bits/socket.h` which is glibc specific. I can also find a different (though equivalent when zero-initializing the padding fields) definition in `/usr/include/x86_64-linux-musl/sys/socket.h` which is musl specific. I can also find the definition used by the kernel on the man page which directly matches glibc it seems: https://man7.org/linux/man-pages/man2/sendmsg.2.html

**Comment by sunfishcode** [comment]
Thanks for working on this!

Yes, that's the best approach when possible. Unfortunately, Linux's headers don't define all the types that participate in Linux's ABI, so this crate also contains a header, `gen/modules/general.h`, which includes Linux headers for everything it can, and manually defines things that are missing.

At a brief glance, it looks like Linux's own `msghdr` in <linux/socket.h> is only defined in `__KERNEL__` configurations, so the first step is to add a definition of `msghdr` to `gen/modules/general.h` here. The next step is to regenerate the generated bindings, with the command in the toplevel README.md. Then commit the result and submit a PR :-).
