### ISSUE TITLE
seteuid missing

### ISSUE THREAD

**Issue by SUPERCILEX** [sunfishcode/linux-raw-sys#39]
`setuid` and `setreuid` are present, but `seteuid` is missing for some reason. Same for gid.

**Comment by sunfishcode** [comment]
Linux doesn't have a literal `seteuid` syscall; you have to synthesize it out of some other syscall, though I don't know which one offhand.

**Comment by notgull** [comment]
Musl uses [`__xsetid`](https://github.com/bminor/musl/blob/cfdfd5ea3ce14c6abf7fb22a531f3d99518b5a1b/src/unistd/seteuid.c)

**Comment by sunfishcode** [comment]
Caution is indicated; see the library/kernel differences in the [setresuid docs](https://man7.org/linux/man-pages/man2/setresuid.2.html#NOTES).

**Comment by SUPERCILEX** [comment]
Huh, TIL. I'd say not worth supporting seteuid until someone asks for it.
