### ISSUE TITLE
Better module organization

### ISSUE THREAD

**Issue by bjorn3** [sunfishcode/linux-raw-sys#4]
Currently each module includes the entirety of the syscall interface as of the respective kernel version with all types duplicated between modules. I think it would be nicer to have each module only include the diff with the previous kernel version and maybe a glob re-export of all items of the previous version.

This is probably not very easy to do with bindgen though.

**Comment by sunfishcode** [comment]
Yeah; I don't know of a way to do this with bindgen.

**Comment by sunfishcode** [comment]
This is effectively fixed by #20. We only have one version now, so there's no significant duplication.
