### ISSUE TITLE
umount flags missing

### ISSUE THREAD

**Issue by SUPERCILEX** [sunfishcode/linux-raw-sys#40]
None of the flags on this page seem to exist: https://man7.org/linux/man-pages/man2/umount.2.html

**Comment by sunfishcode** [comment]
Linux is much better about this than it used to be, but its public header files still don't always define all the things one needs to interface with the public ABI. In these cases, we just add the constants to a header file ourselves and wit-bindgen that :-).

**Comment by sunfishcode** [comment]
Fixed in 0.2.1.

**Comment by SUPERCILEX** [comment]
Weird, thanks for fixing this! :heart:
