### ISSUE TITLE
Add CAP_* constants?

### ISSUE THREAD

**Issue by SUPERCILEX** [sunfishcode/linux-raw-sys#41]
They're currently hardcoded in rustix which seems odd. Ideally they'd be auto-generated here.

**Comment by sunfishcode** [comment]
Ooh, good point. Added in #42.

**Comment by SUPERCILEX** [comment]
Awesome, thank you! I'm working on cap{get,set}, so I'll fix the constants situation in there.

**Comment by sunfishcode** [comment]
Fixed in 0.2.1.
