### ISSUE TITLE
Add support for select() macros

### ISSUE THREAD

**Issue by notgull** [sunfishcode/linux-raw-sys#44]
Looking at this crate on `docs.rs`, the macros for the `select` function (`FD_SET`, `FD_ISSET` etc) don't exist. However, it doesn't look like `fd_set` exists either. Would you mind if I added support for these macros/types to this crate?

**Comment by sunfishcode** [comment]
It does have [`__kernel_fd_set`](https://docs.rs/linux-raw-sys/latest/linux_raw_sys/general/struct.__kernel_fd_set.html). Adding the `FD_SET` etc. operations sounds reasonable.
