### ISSUE TITLE
Signal handler union in `sigaction` on x86_64

### ISSUE THREAD

**Issue by jordanisaacs** [sunfishcode/linux-raw-sys#47]
The generated bindings to `sigaction` does not pick up that the handler can be a union of either `f(int)` or `f(int, siginfo_t, void/ucontext)`. See man(2) sigaction. This may not be an issue with the generated bindings as it seems it is not defined as a union for `x86_64` architecture: https://sourcegraph.com/github.com/torvalds/linux/-/blob/arch/x86/include/uapi/asm/signal.h?L82%3A12=

Not sure if it should be manually updated in linux-raw-sys or just create my own `sigaction` struct?

**Comment by sunfishcode** [comment]
The generated bindings reflect what the kernel headers contain. I don't know why it's defined as a union on 32-bit x86 and nothing else. This seems awkward to fix in linux-raw-sys, so perhaps either define your own `sigaction` struct or just cast the function pointer as needed?

**Comment by jordanisaacs** [comment]
Sounds good to me. I just made my own `sigaction` and will continue with that. All the struct/types needed to do it already exist in `linux_raw_sys` which is nice.

**Comment by jordanisaacs** [comment]
Sounds good to me. I just made my own `sigaction` and will continue with that. All the struct/types needed to do it already exist in `linux_raw_sys` which is nice.
